// Lista curada dos CNAEs mais comuns (código, descrição, anexo do Simples).
// Não é a tabela completa — cobre as atividades mais buscadas. Consulte a Nauta para o seu caso.
export interface Cnae { codigo: string; descricao: string; anexo: string }

export const CNAES: Cnae[] = [
  { codigo: '4712-1/00', descricao: 'Comércio varejista de mercadorias em geral (minimercado, mercearia)', anexo: 'I' },
  { codigo: '4781-4/00', descricao: 'Comércio varejista de artigos do vestuário e acessórios', anexo: 'I' },
  { codigo: '4772-5/00', descricao: 'Comércio varejista de cosméticos, produtos de perfumaria e higiene', anexo: 'I' },
  { codigo: '4771-7/01', descricao: 'Comércio varejista de produtos farmacêuticos (farmácia)', anexo: 'I' },
  { codigo: '4753-9/00', descricao: 'Comércio varejista de eletrodomésticos e equipamentos de áudio e vídeo', anexo: 'I' },
  { codigo: '4744-0/99', descricao: 'Comércio varejista de materiais de construção em geral', anexo: 'I' },
  { codigo: '5611-2/01', descricao: 'Restaurantes e similares', anexo: 'I' },
  { codigo: '5611-2/03', descricao: 'Lanchonetes, casas de chá, de sucos e similares', anexo: 'I' },
  { codigo: '5620-1/04', descricao: 'Fornecimento de alimentos preparados (marmitaria, delivery)', anexo: 'I' },
  { codigo: '4520-0/01', descricao: 'Serviços de manutenção e reparação mecânica de veículos', anexo: 'III' },
  { codigo: '9602-5/01', descricao: 'Cabeleireiros, manicure e pedicure (salão de beleza)', anexo: 'III' },
  { codigo: '9602-5/02', descricao: 'Atividades de estética e cuidados com a beleza', anexo: 'III' },
  { codigo: '8630-5/03', descricao: 'Atividade médica ambulatorial com recursos para exames complementares', anexo: 'III ou V (Fator R)' },
  { codigo: '8630-5/01', descricao: 'Atividade médica ambulatorial (consultório médico)', anexo: 'III ou V (Fator R)' },
  { codigo: '8650-0/03', descricao: 'Atividades de psicologia e psicanálise', anexo: 'III ou V (Fator R)' },
  { codigo: '8650-0/04', descricao: 'Atividades de fisioterapia', anexo: 'III ou V (Fator R)' },
  { codigo: '8650-0/02', descricao: 'Atividades de profissionais da nutrição', anexo: 'III ou V (Fator R)' },
  { codigo: '8630-5/04', descricao: 'Atividade odontológica (dentista)', anexo: 'III ou V (Fator R)' },
  { codigo: '6920-6/01', descricao: 'Atividades de contabilidade', anexo: 'III ou V (Fator R)' },
  { codigo: '6911-7/01', descricao: 'Serviços advocatícios', anexo: 'IV' },
  { codigo: '7112-0/00', descricao: 'Serviços de engenharia', anexo: 'III ou V (Fator R)' },
  { codigo: '7111-1/00', descricao: 'Serviços de arquitetura', anexo: 'III ou V (Fator R)' },
  { codigo: '6201-5/01', descricao: 'Desenvolvimento de programas de computador sob encomenda', anexo: 'III ou V (Fator R)' },
  { codigo: '6202-3/00', descricao: 'Desenvolvimento e licenciamento de softwares customizáveis', anexo: 'III ou V (Fator R)' },
  { codigo: '6209-1/00', descricao: 'Suporte técnico, manutenção e outros serviços em TI', anexo: 'III ou V (Fator R)' },
  { codigo: '7319-0/03', descricao: 'Marketing direto', anexo: 'III ou V (Fator R)' },
  { codigo: '7311-4/00', descricao: 'Agências de publicidade', anexo: 'III ou V (Fator R)' },
  { codigo: '7020-4/00', descricao: 'Consultoria em gestão empresarial', anexo: 'III ou V (Fator R)' },
  { codigo: '8599-6/04', descricao: 'Treinamento em desenvolvimento profissional e gerencial', anexo: 'III ou V (Fator R)' },
  { codigo: '8513-9/00', descricao: 'Ensino fundamental / educação (escola)', anexo: 'III' },
  { codigo: '8592-9/99', descricao: 'Ensino de arte e cultura (curso livre)', anexo: 'III' },
  { codigo: '9313-1/00', descricao: 'Atividades de condicionamento físico (academia)', anexo: 'III' },
  { codigo: '4530-7/03', descricao: 'Comércio a varejo de peças e acessórios para veículos', anexo: 'I' },
  { codigo: '4713-0/02', descricao: 'Lojas de variedades, exceto lojas de departamentos', anexo: 'I' },
  { codigo: '4789-0/99', descricao: 'Comércio varejista de outros produtos não especificados', anexo: 'I' },
  { codigo: '4930-2/02', descricao: 'Transporte rodoviário de carga intermunicipal e interestadual', anexo: 'III' },
  { codigo: '5320-2/02', descricao: 'Serviços de entrega rápida (motoboy)', anexo: 'III' },
  { codigo: '4321-5/00', descricao: 'Instalações elétricas', anexo: 'III' },
  { codigo: '4322-3/01', descricao: 'Instalações hidráulicas, sanitárias e de gás', anexo: 'III' },
  { codigo: '4330-4/04', descricao: 'Serviços de pintura de edifícios em geral', anexo: 'III' },
  { codigo: '9511-8/00', descricao: 'Reparação e manutenção de computadores e periféricos', anexo: 'III' },
  { codigo: '7420-0/01', descricao: 'Atividades de produção de fotografia (fotógrafo)', anexo: 'III' },
  { codigo: '7490-1/04', descricao: 'Atividades de intermediação e agenciamento de serviços', anexo: 'III ou V (Fator R)' },
  { codigo: '8219-9/99', descricao: 'Preparação de documentos e apoio administrativo', anexo: 'III' },
  { codigo: '4110-7/00', descricao: 'Incorporação de empreendimentos imobiliários', anexo: 'I' },
  { codigo: '6821-8/01', descricao: 'Corretagem na compra e venda e avaliação de imóveis', anexo: 'III ou V (Fator R)' },
  { codigo: '5510-8/01', descricao: 'Hotéis', anexo: 'III' },
  { codigo: '7911-2/00', descricao: 'Agências de viagens', anexo: 'III' },
  { codigo: '4791-1/00', descricao: 'Comércio varejista pela internet (e-commerce)', anexo: 'I' },
  { codigo: '4799-9/99', descricao: 'Comércio varejista fora de estabelecimento (revendedor)', anexo: 'I' },
]
